### ISSUE TITLE
Issue in Compilation

### ISSUE THREAD

**Issue by rsidhaarth** [Instamojo/instamojo-magento-2#8]
Hi All,

Executing this command gives the below error "php -f bin/magento setup:di:compile"

root@localhost:/srv/users/public# php -f bin/magento setup:di:compile
Compilation was started.
Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 46.0 MiBPHP Fatal error:  Cannot declare class CurlException, because the name is already in use in /srv/users/public/vendor/instamojo/instamojo-magento-2/lib/CurlException.php on line 25

Fatal error: Cannot declare class CurlException, because the name is already in use in /srv/users/public/vendor/instamojo/instamojo-magento-2/lib/CurlException.php on line 25

**Comment by ashwch** [comment]
Could you please try clearing `var/generation folder` folder and then run `php bin/magento cache:flush`.  Now try running `php -f bin/magento setup:di:compile` again.

**Comment by rsidhaarth** [comment]
Hi,

I tried it and it doesn’t work. I am using PHP 7.0.23

Thanks
